language: generic

git:
  depth: 3

services:
  - docker

before_install:
  - time docker pull openmodelica/openmodelica:v1.12.0-minimal
  - time docker pull openmodelica/moparser:xenial

script:
  - docker run -v "$PWD:/repo" -w "/repo" openmodelica/openmodelica:v1.12.0-minimal omc .travis.mos
  - "! find . -name '*.mo' -exec bash -c 'iconv -o /dev/null -f ascii -t ascii \"{}\" |& sed \"s,^,{}: ,\"' ';' | grep '.'"
  - docker run -v "$PWD:/repo" -w "/repo" openmodelica/moparser:xenial moparser -v 3.2 -r VehicleInterfaces

notifications:
  email: false
