language: generic
services:
  - docker
before_install:
  - time docker pull openmodelica/openmodelica:v1.12.0-minimal
  - time docker pull openmodelica/moparser:xenial
script:
  - docker run -v "$PWD:/repo" -w "/repo" openmodelica/openmodelica:v1.12.0-minimal omc .travis.mos
  - docker run -v "$PWD:/repo" -w "/repo" openmodelica/moparser:xenial moparser -r VehicleInterfaces
